
spring:
  dubbo:
    scan: com.krly.api.impl
    application:
      name: message-handler
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 14116
    provider:
      retries: 0